#version: '3'
#
#services:
#  web:
#    build: .
##    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
##    container_name: app
##    container_name: app
#    volumes:
#      - .:/app
#    ports:
#      - "8000:8000"
version: '3'

services:
  web:
    build: ./
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
