# Generated by Django 2.2.7 on 2019-11-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmodel',
            name='text',
            field=models.CharField(max_length=1024),
        ),
    ]
