# Generated by Django 2.2.7 on 2019-11-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191112_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmodel',
            name='text',
            field=models.TextField(),
        ),
    ]
