# Generated by Django 2.2.7 on 2019-11-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191112_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmodel',
            name='model_name',
            field=models.CharField(default='RandomForest', max_length=32),
        ),
        migrations.AddField(
            model_name='textmodel',
            name='vectorizer',
            field=models.CharField(default='TfIDF', max_length=32),
        ),
    ]
