# Generated by Django 2.2.7 on 2019-11-12 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191112_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textmodel',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='textmodel',
            name='vectorizer',
        ),
    ]
