# Generated by Django 2.2.7 on 2019-11-12 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191112_0941'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TextModel',
        ),
    ]
