# Generated by Django 2.2.7 on 2019-11-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0006_delete_textmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('model_name', models.CharField(max_length=64)),
                ('vectorizer', models.CharField(max_length=64)),
                ('load_path', models.CharField(default='/home/stefan/PycharmProjects/text_clf/ml/models', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TrainModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_data', models.FilePathField()),
                ('train_labels', models.FilePathField()),
                ('model_name', models.CharField(max_length=64)),
                ('vectorizer', models.CharField(max_length=64)),
                ('save_path', models.CharField(default='/home/stefan/PycharmProjects/text_clf/ml/models', max_length=256)),
            ],
        ),
    ]
