# Generated by Django 2.2.7 on 2019-11-12 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_predictmodel_trainmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainmodel',
            name='train_data',
        ),
        migrations.RemoveField(
            model_name='trainmodel',
            name='train_labels',
        ),
    ]
