# Generated by Django 2.2.7 on 2019-11-12 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191112_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainmodel',
            name='train_data',
            field=models.FilePathField(default=django.utils.timezone.now, path='/home/stefan/PycharmProjects/text_clf/ml/models'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainmodel',
            name='train_labels',
            field=models.FilePathField(default=django.utils.timezone.now, path='/home/stefan/PycharmProjects/text_clf/ml/models'),
            preserve_default=False,
        ),
    ]
