# Generated by Django 2.2.7 on 2019-11-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20191112_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictmodel',
            name='model_name',
            field=models.CharField(choices=[('RandomForest', 'RandomForest'), ('SVM', 'SVM'), ('XGB', 'XGB'), ('NaiveBayes', 'NaiveBayes')], max_length=64),
        ),
        migrations.AlterField(
            model_name='predictmodel',
            name='vectorizer',
            field=models.CharField(choices=[('TfIdf', 'TfIdf'), ('CV', 'CV')], max_length=64),
        ),
        migrations.AlterField(
            model_name='trainmodel',
            name='model_name',
            field=models.CharField(choices=[('RandomForest', 'RandomForest'), ('SVM', 'SVM'), ('XGB', 'XGB'), ('NaiveBayes', 'NaiveBayes')], max_length=64),
        ),
        migrations.AlterField(
            model_name='trainmodel',
            name='vectorizer',
            field=models.CharField(choices=[('TfIdf', 'TfIdf'), ('CV', 'CV')], max_length=64),
        ),
    ]
