# Generated by Django 2.2.7 on 2019-11-12 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20191112_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictmodel',
            name='text',
        ),
    ]
