# Generated by Django 2.2.7 on 2019-11-12 19:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_predictmodel_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictmodel',
            name='text',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
